version: '3.9'

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  worker:
    build: .
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/1
    volumes:
      - .:/app
    command: ./run_worker.sh
